###################################################################################################
############################ MOREIRA LAB - DATA DRIVEN MOLECULAR DESIGN ###########################
###################################################################################################

#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent
AA_GROUPS = {
    'nonpolar_aliphatic': list('AVLIM'),
    'aromatic': list('FYW'),
    'basic_positive': list('KRH'),
    'acidic_negative': list('DE'),
    'polar_uncharged': list('STNQCGP'),
}
GROUP_ORDER = list(AA_GROUPS.keys())
AA_ORDER = list('AGILMVFYWNCQPSTDERHK')


def _find_file(candidates):
    for c in candidates:
        p = ROOT / c
        if p.exists():
            return p
    return None


def _normalise_side(x: str) -> str:
    x = str(x).lower()
    if 'rec' in x or 'gpcr' in x or 'or_' in x or x == 'r':
        return 'receptor'
    if 'part' in x or 'gprot' in x or 'arr' in x or x == 'p':
        return 'partner'
    return x


def load_interface_percentages() -> pd.DataFrame:
    """Load amino-acid interface percentages generated by the rebuilt pipeline.

    Accepted formats:
    1) long table with columns: complex, side, aa, percentage
    2) wide table with columns: complex, side, A, C, D, ...
    3) separate receptor/partner CSVs with AA columns.
    """
    candidates = [
        'processed_results/interface_amino_acid_percentages.csv',
        'processed_results/interface_aa_percentages.csv',
        'summary/interface_amino_acid_percentages.csv',
        'summary/interface_aa_percentages.csv',
    ]
    p = _find_file(candidates)
    if p:
        df = pd.read_csv(p)
        cols = {c.lower(): c for c in df.columns}
        if {'complex','side','aa','percentage'}.issubset(cols):
            out = df.rename(columns={cols['complex']:'complex', cols['side']:'side', cols['aa']:'aa', cols['percentage']:'percentage'})
            out['side'] = out['side'].map(_normalise_side)
            return out[['complex','side','aa','percentage']]
        # wide format
        aa_cols = [c for c in df.columns if str(c).upper() in AA_ORDER]
        complex_col = cols.get('complex') or cols.get('complex_name') or cols.get('model') or df.columns[0]
        side_col = cols.get('side') or cols.get('interface_side')
        if aa_cols and side_col:
            out = df.melt(id_vars=[complex_col, side_col], value_vars=aa_cols, var_name='aa', value_name='percentage')
            out = out.rename(columns={complex_col:'complex', side_col:'side'})
            out['side'] = out['side'].map(_normalise_side)
            return out[['complex','side','aa','percentage']]

    # separate files fallback
    pairs = [
        ('processed_results/interface_percentages_receptor.csv', 'receptor'),
        ('processed_results/interface_percentages_partner.csv', 'partner'),
        ('summary/interface_percentages_receptor.csv', 'receptor'),
        ('summary/interface_percentages_partner.csv', 'partner'),
    ]
    frames = []
    for rel, side in pairs:
        p = ROOT / rel
        if not p.exists():
            continue
        df = pd.read_csv(p)
        aa_cols = [c for c in df.columns if str(c).upper() in AA_ORDER]
        if not aa_cols:
            continue
        complex_col = 'complex' if 'complex' in df.columns else df.columns[0]
        tmp = df.melt(id_vars=[complex_col], value_vars=aa_cols, var_name='aa', value_name='percentage')
        tmp = tmp.rename(columns={complex_col:'complex'})
        tmp['side'] = side
        frames.append(tmp)
    if frames:
        return pd.concat(frames, ignore_index=True)[['complex','side','aa','percentage']]

    raise FileNotFoundError('Could not find interface amino-acid percentage table. Run python call.py first.')


def aa_to_group(aa: str) -> str:
    aa = str(aa).upper().strip()
    for g, aas in AA_GROUPS.items():
        if aa in aas:
            return g
    return 'other'


def plot_group_heatmap(df: pd.DataFrame, side: str, outprefix: Path) -> Path:
    d = df[df['side'].eq(side)].copy()
    if d.empty:
        raise ValueError(f'No rows found for side={side}')
    d['aa_group'] = d['aa'].map(aa_to_group)
    g = d.groupby(['aa_group','complex'], dropna=False)['percentage'].sum().reset_index()
    mat = g.pivot(index='aa_group', columns='complex', values='percentage').fillna(0.0)
    order = [x for x in GROUP_ORDER if x in mat.index] + [x for x in mat.index if x not in GROUP_ORDER]
    mat = mat.loc[order]

    outprefix.parent.mkdir(parents=True, exist_ok=True)
    plt.figure(figsize=(max(12, 0.16 * mat.shape[1]), 3.8))
    im = plt.imshow(mat.values, aspect='auto')
    plt.yticks(range(len(mat.index)), mat.index)
    plt.xticks(range(len(mat.columns)), mat.columns, rotation=90, fontsize=6)
    plt.colorbar(im, label='Interface percentage')
    plt.title(f'Figure S2-style chemical-group interface percentages: {side} side')
    plt.tight_layout()
    png = outprefix.with_suffix('.png')
    svg = outprefix.with_suffix('.svg')
    plt.savefig(png, dpi=300)
    plt.savefig(svg)
    plt.close()
    mat.to_csv(ROOT / 'summary' / f'interface_group_percentages_{side}.csv')
    return png


def run_all():
    df = load_interface_percentages()
    (ROOT/'summary').mkdir(exist_ok=True)
    outs = []
    outs.append(plot_group_heatmap(df, 'receptor', ROOT/'images/figure_s2_groups_receptor'))
    outs.append(plot_group_heatmap(df, 'partner', ROOT/'images/figure_s2_groups_partner'))
    return outs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--side', choices=['receptor','partner','both'], default='both')
    args = ap.parse_args()
    df = load_interface_percentages()
    (ROOT/'summary').mkdir(exist_ok=True)
    if args.side in {'receptor','both'}:
        print(plot_group_heatmap(df, 'receptor', ROOT/'images/figure_s2_groups_receptor'))
    if args.side in {'partner','both'}:
        print(plot_group_heatmap(df, 'partner', ROOT/'images/figure_s2_groups_partner'))

if __name__ == '__main__':
    main()
